/* empty css                      */(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(e){if(e.ep)return;e.ep=!0;const n=s(e);fetch(e.href,n)}})();const c="daily-quote";async function u(){const o=JSON.parse(localStorage.getItem(c)),r=new Date().toLocaleDateString();if(o&&o.date===r){i(o.quote,o.author);return}try{const t=await(await fetch("https://your-energy.b.goit.study/api/quote")).json(),e={quote:t.quote,author:t.author,date:r};localStorage.setItem(c,JSON.stringify(e)),i(t.quote,t.author)}catch(s){console.log("Помилка отримання цитати:",s)}}function i(o,r){const s=document.querySelector(".quote-text"),t=document.querySelector(".quote-author");s&&t&&(s.textContent=o,t.textContent=r)}async function l(){try{const r=await(await fetch("https://your-energy.b.goit.study/api/filters?filter=Muscles&page=1&limit=12")).json();d(r.results)}catch(o){console.log("Помилка отримання фільтрів:",o)}}function d(o){const r=document.querySelector(".exercises-container");if(!r)return;const s=o.map(t=>`
    <li class="filter-card" data-filter="${t.filter}" data-name="${t.name}" 
        style="background: linear-gradient(0deg, rgba(16, 16, 16, 0.7), rgba(16, 16, 16, 0.7)), url('${t.imgUrl}'); background-size: cover;">
      <div class="filter-card-content">
        <p class="filter-card-name">${t.name.toUpperCase()}</p>
        <p class="filter-card-type">${t.filter}</p>
      </div>
    </li>
  `).join("");r.innerHTML=s}u();l();
//# sourceMappingURL=index.js.map
